### ISSUE TITLE
RAC fire rate with UAC double tap disabled behaves extremely strange

### ISSUE THREAD

**Issue by Tyler799** [fat4eyes-mwo/mwo-simulator#19] opened 2017-09-21 22:59 UTC
The RAC bar fills up just as normally, but the fire rate seems to be half of what it is normally.

**Comment by fat4eyes-mwo** [comment] 2017-12-28 01:24
Confirmed. Will see what causes it.

**Comment by fat4eyes-mwo** [comment] 2017-12-28 06:12
Should be fixed in https://github.com/fat4eyes-mwo/mwo-simulator/commit/57a7731e2f0cdc4f8be470557c3f988870895f44

Was caused by overly broad condition check when double tap was disabled (it also affected non-doubletap weapons)

**Closed as completed by fat4eyes-mwo** 2017-12-28 06:12 UTC
Labels: bug
